security:
  jwt:
    secret-key: verysecretkeyohmygodwhyisitsosecretdonttellanybody

spring:
  application:
    name: Mocha Money
  datasource:
    url: jdbc:mysql://localhost:3306/mochamoney
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
